### ISSUE TITLE
Reading and writing non-ASCII characters

### ISSUE THREAD

**Issue by phonixor** [ropensci/readODS#1]
cell values containing "" turn into  â€â€, this seems to happen on windows only (tested on ubuntu and win7)

its probably an encoding issue...
but the unz and open commands seem to ignore the encoding parameters...

**Comment by chainsawriot** [comment]
Tested. A merged cell can jam the parsing and produce incorrect data.

http://postimg.org/image/5tsbqyb8t/

Need to look into that or notes it in the documentation.

**Comment by MichalLauer** [comment]
I tried to replicate this issue, but it looks like it's already fixed as some special characters as well as " are correctly written and read :)

``` r
library(readODS)
#> Warning: package 'readODS' was built under R version 4.2.2
x <- data.frame(col = c("č", "\"", "š"))
write_ods(x, "test.ods")
read_ods("test.ods")
#>   col
#> 1   č
#> 2   "
#> 3   š
sessionInfo()
#> R version 4.2.0 (2022-04-22 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Czech_Czechia.utf8  LC_CTYPE=Czech_Czechia.utf8   
#> [3] LC_MONETARY=Czech_Czechia.utf8 LC_NUMERIC=C                  
#> [5] LC_TIME=Czech_Czechia.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] readODS_1.7.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.2.0    pillar_1.8.1      highr_0.10        R.methodsS3_1.8.2
#>  [5] R.utils_2.12.2    tools_4.2.0       digest_0.6.31     evaluate_0.19    
#>  [9] lifecycle_1.0.3   tibble_3.1.8      R.cache_0.16.0    pkgconfig_2.0.3  
#> [13] rlang_1.0.6       reprex_2.0.2      cli_3.6.0         rstudioapi_0.14  
#> [17] yaml_2.3.6        xfun_0.36         fastmap_1.1.0     withr_2.5.0      
#> [21] styler_1.8.1      stringr_1.5.0     knitr_1.41        xml2_1.3.3       
#> [25] fs_1.5.2          vctrs_0.5.1       hms_1.1.2         glue_1.6.2       
#> [29] R6_2.5.1          fansi_1.0.3       rmarkdown_2.19    purrr_1.0.1      
#> [33] readr_2.1.3       tzdb_0.3.0        magrittr_2.0.3    htmltools_0.5.4  
#> [37] ellipsis_0.3.2    utf8_1.2.2        stringi_1.7.12    crayon_1.5.2     
#> [41] R.oo_1.25.0
```

<sup>Created on 2023-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Does it make sense to close this one @chainsawriot ?

**Comment by chainsawriot** [comment]
@MichalLauer I think @phonixor was mentioning an ancient version of readODS (using XML; without `write_ods`). Probably this issue has been fixed during the 2016 rewrite. 

I agree with you that this issue can be closed. But a more pragmatic approach is to turn these into tests so that it won't recur.

Inclusion of non-ASCII characters in R package is not trivial. One way is to declare this package depends on R >= 4.2. Another way is to use `stringi::stri_escape_unicode` to convert non-ASCII characters into "CRAN-safe" version.

\u010d
\u0161
\u00c4
\u5b57
\u30a2
\u30a2\u30e0\u30ed

```r
content <- c("\"", "\u010d", "\u0161", "\u00c4", "\u5b57", "\u30a2", "\u30a2\u30e0\u30ed")
x <- data.frame(col = content)
ascii_test_file <- tempfile(fileext = ".ods")
readODS::write_ods(x, ascii_test_file)
y <- readODS::read_ods(ascii_test_file)
testthat::expect_equal(content, y$col)
```

The problem is: This test case passes with the current CRAN version (1.7) but not the current RC (1.8). It indicates the new write function is not thoroughly tested.

First, it will delay the release of 1.8; second, I need to find out why 37e9c17e859a7ded78566325f183773b35807a20 won't work.

**Comment by MichalLauer** [comment]
Hello @chainsawriot,

I'm not sure how I can help you with this. If you need some help, feel free to reach out:)

**Comment by chainsawriot** [comment]
Small update:

This actually works

```r
content <- c("\u010d", "\u0161", "\u00c4", "\u5b57", "\u30a2", "\u30a2\u30e0\u30ed")
x <- data.frame(col = content)
ascii_test_file <- tempfile(fileext = ".ods")
readODS::write_ods(x, ascii_test_file)
y <- readODS::read_ods(ascii_test_file)
testthat::expect_equal(content, y$col)
```

The whole problem is actually from `"`. This narrow down the problem space.

**Comment by chainsawriot** [comment]
This is valid:

```xml
          <table:table-cell office:value-type="string" office:value="&quot;" table:style-name="ce1">
            <text:p>"</text:p>

```

This is the invalid version generated by the current 1.8RC

```r
          <table:table-cell office:value-type="string" office:value=""" table:style-name="ce1">
            <text:p>"</text:p>
```

The current implementation doesn't do [XML escaping](https://www.w3.org/TR/xml11/#sec-predefined-ent). Good news is, there are only five.

**Comment by chainsawriot** [comment]
In another words, we need to properly fuzz the 1.8RC.
