### ISSUE TITLE
NAs silently written as zeros in numeric columns

### ISSUE THREAD

**Issue by ne1s0n** [ropensci/readODS#104]
When writing any NAs in numeric columns are silently converted to zeros. Minimal working example:

```
library(readODS)
testdf = data.frame(
  col1 = c('foo', NA, 'baz'),
  col2 = c(1, 2, NA)
)

#col1 is written correctly as "foo" "NA" baz"
#col2 is written as 1, 2, 0
write_ods(testdf, 'test.ods')
```

**Comment by chainsawriot** [comment]
@ne1s0n Thank you for the report.

This problem has been fixed recently: #79

To keep the long story short: there is no best way to write NA as numeric that Libreoffice can recognized.

In the future version, we will treat NA either as string or empty.

But for now, if you are using the GitHub version:

```r
write_ods(testdf, 'test.ods', na_as_string = TRUE)
## if you want it to be the default, put this in your R init file:
## option("write_ods_na" = TRUE)
```
