### ISSUE TITLE
Can't write to tempfile (permission denied) when using write_ods()

### ISSUE THREAD

**Issue by ktiu** [ropensci/readODS#105]
When using the `write_ods()` function it seems that the temp files are created with insufficient permissions to complete the process.

```
> readODS::write_ods(mtcars, "test.ods")
Error in file(file.path(temp_ods_dir, "content.xml"), open = "w") :
  cannot open the connection
In addition: Warning message:
In file(file.path(temp_ods_dir, "content.xml"), open = "w") :
  cannot open file '/tmp/RtmpIiv6gz/YZhIY0vtLj1inF73TJ2x/content.xml': Permission denied
```

Inspecting the file gives:

```
$ ls -la /tmp/RtmpIiv6gz/YZhIY0vtLj1inF73TJ2x/
.r--r--r-- 2.1k till 24 May 15:46 content.xml
dr-xr-xr-x    - till 24 May 15:46 META-INF
.r--r--r--  629 till 24 May 15:46 meta.xml
.r--r--r--   46 till 24 May 15:46 mimetype
.r--r--r-- 2.6k till 24 May 15:46 styles.xml
```

I'm using readODS version 1.8.0 and R version 4.2.3 on NixOS.

**Comment by chainsawriot** [comment]
@ktiu Thanks for reporting this. I don't use NixOS, could you try this?

```r
file(tempfile(), open = "w")
```

To be honest, I don't know enough NixOS to diagnose what the problem is. Do you have an idea?

**Comment by ktiu** [comment]
Of course!

The command gives

```
> file(tempfile(), open = "w")
A connection with
description "/tmp/RtmpotOrd7/filebee9167eccff3"
class       "file"
mode        "w"
text        "text"
opened      "opened"
can read    "no"
can write   "yes"
```

And the created file does indeed have write permissions (unlike `content.xml` above):

```
$ ls -la /tmp/RtmpotOrd7/
.rw-r--r-- 0 till 15 Jun 00:33 filebee9167eccff3
```

Digging into this a bit I have the following suspicion:

The function .vfwrite_ods which seems to be throwing the error first copies a template dir from the package directory in [line 103](https://github.com/ropensci/readODS/blob/15da5ae56ee9b53781565f613dc3aca5b8116fd1/R/writeODS.R#L103):

```
templatedir <- system.file("template", package = "readODS")
file.copy(dir(templatedir, full.names = TRUE), temp_ods_dir, recursive = TRUE)
```

The template dir points to the Nix store, which is mounted read-only:

```
$ ls -la /nix/store/p6ldbkhkyprqcz4alym4wakblmzzql11-r-readODS-1.8.0/library/readODS/template
.r--r--r-- 2.1k root  1 Jan  1970 content.xml
dr-xr-xr-x    - root  1 Jan  1970 META-INF
.r--r--r--  629 root  1 Jan  1970 meta.xml
.r--r--r--   46 root  1 Jan  1970 mimetype
.r--r--r-- 2.6k root  1 Jan  1970 styles.xml
```

A solution would be to provide  `copy.mode = FALSE` to the `file.copy()` function call, if you can't think of any reason why this may cause problems. I tested it and it works, will create a pull request.
