### ISSUE TITLE
Renaming is not predictable

### ISSUE THREAD

**Issue by pbrohan** [ropensci/readODS#115]
Sorry, this is my fault.

As well as the issues in #114 , we **also** have the argument `check_names` which interacts with `data.frame`. 

It's theoretically fine (if `check_names` is `FALSE`, and we export to a tibble with `.name_repair = "unique"`, the tibble will have column names generated by `tibble:::repaired_names()`. If `check_names` is `TRUE`, the names will be repaired using  `make.names( , unique = TRUE)`,), it's just very easy for two people to import the same file and get different column names, i.e.

``` r
r$> tibble:::repaired_names(c(NA_character_,NA), repair_hint = TRUE, .name_repair = "unique")
# [1] "...1" "...2"

r$> make.names(c(NA_character_, NA), unique = TRUE)
# [1] "NA."  "NA..1"
```

### Option 1

If `as_tibble` is going be the default, maybe removing the flag for `check_names` is simplest, and instead, if `as_tibble` is `FALSE` : 
- if `.name_repair` is `"minimal"`, do nothing, 
- if `.name_repair` is `"check_unique"` throw `stop("Names must be unique. Column name %name% must not be duplicated")`
- if `.name_repair` is `"unique"` run the names through `make.unique(x)`
- if `.name_repair` is `"universal"` run the names through `make.names(x, unique = "TRUE")`

if `as_tibble = TRUE` then just pass `.name_repair` over to `as_tibble`. 

While you would still get different names for data.frames and tibbles, these are more likely the names that people are expecting.

### Option 2

Or we could do the above even if the df is being converted to a tibble. Then all names are internally consistent although not very tidyverse

### Option 3

Or keep things as they are

Any preference? I'll happily write a PR for any.

**Comment by chainsawriot** [comment]
@pbrohan No worries. `as_tibble` = `TRUE` is going to be the default in v2 (as `read_ods` is trying to match `readxl::read_xlsx` and v2 is breaking anyway), so your Option 1 (removing `check_names` #92) is the best option.
