### ISSUE TITLE
Make `col_types` easier to use

### ISSUE THREAD

**Issue by chainsawriot** [ropensci/readODS#135]
read [this review](https://druedin.com/2020/06/11/readods-and-column-specifications/) of the package.

> The [R package readODS](https://cran.r-project.org/package=readODS) allows you to import ODS spreadsheets to R. It’s slow, but it works. In an attempt to speed up things, I thought providing column types would help. I didn’t find an improvement, but I noticed that the documentation wasn’t really clear (“refer to readr::type_convert to specify cols specification”). It seems like you do need to refer to type_convert to understand how to specify column types, and then feed them to readODS like this:

readxl can accept [more options](https://readxl.tidyverse.org/articles/cell-and-column-types.html).

**Comment by pbrohan** [comment]
I did look at this a little bit, but the way that readxl does it is very complicated, as it performs its own type checking in C++.

We could also do this, and in particular this would help to solve #97, which is very difficult to solve with the current method of type checking), but it would constitute a major breaking change (and also probably take a while). Sadly we can't just steal the way that `readxl` does it, as it's baked into their method of reading excel files. 

`readr` itself is actually pretty fast, (for further speed improvements I think that improving the C++ code is likely to give more of a speed increase than moving away from readr) and so possibly some kind of shim that allows for readxl style column specs without having to learn to use readr might work temporarily (although it'd be better just to rewrite the code in general)

**Comment by chainsawriot** [comment]
@pbrohan Thank you very much! I think we should stick with `readr` for now.

A quick fix to this is to improve the doc.

* Saying specifying `col_types` won't improve speed by a lot; rather accuracy.
* Give examples such as: `read_ods("starwars.ods", sheet = 2, col_types = readr::cols(gender = "f"))`
* Better yet, reexport `readr::cols`
* Relax the check: `readr::type_convert` allows character and list as `col_types` also.

https://github.com/ropensci/readODS/blob/bd80e4b09fac513f9ab932479833fdf058d5da0f/R/read_ods.R#L205-L214
