### ISSUE TITLE
Name repair does not function as expected

### ISSUE THREAD

**Issue by mafw** [ropensci/readODS#170]
After the update to V2.0.0, when `read_ods` was changed to output tibbles as default, and name repairs were delegated to   `vctrs::vec_as_names()`, column naming is not function as expected. 

To illustrate I have used the data file for testing naming found here:

https://github.com/ropensci/readODS/blob/v2.1/tests/testdata/test_naming.ods

I've used Excel to save an `.xlsx`version of the file to show how the behavior is different when reading using `readxl::read_xlsx` and `readODS::read_ods`, even though both should use `vctrs::vec_as_names()`. 

As the output below shows, `read_ods` disregards the `.name_repair` argument and changes column names. `read_xlsx` behaves as expected and leaves column names unchanged.  

This bug should be detected by the test on line 42 in the `test_read_ods.R` script:
```
expect_silent(x <- read_ods("../testdata/test_naming.ods", .name_repair = "minimal"))`
```
As reading in column 2 and 3 shouldn't be silent. However, as the output below shows, renaming occurs without any information.

Not sure what is going on here, but it seems to me that the `.name_repair` argument is not being passed on to `tibble::as_tibble()``correctly.

```
library(readODS)
library(readxl)

read_ods("test_naming.ods", .name_repair = "minimal")
# A tibble: 5 × 3
      a a.1   Var.3 
  <dbl> <chr> <chr> 
1     1 Val 1 Miss 1
2     2 Val 2 Miss 2
3     3 Val 3 Miss 3
4     4 Val 4 Miss 4
5     5 Val 5 Miss 5

readxl::read_xlsx("test_naming.xlsx", .name_repair = "minimal")
# A tibble: 5 × 3                                                                     
      a a     ``    
  <dbl> <chr> <chr> 
1     1 Val 1 Miss 1
2     2 Val 2 Miss 2
3     3 Val 3 Miss 3
4     4 Val 4 Miss 4
5     5 Val 5 Miss 5
```

**Comment by pbrohan** [comment]
I think this is because of the `data.frame()` here
https://github.com/ropensci/readODS/blob/d9a2787679b353879b9f429d0bc68cdcabb62c90/R/read_ods.R#L239

which ignores the name repair settings set in the line above, so will try to sanitise the column names. Probably preferable to sanitise the output of `.change_df_with_col_row_header` to always output a `data.frame` so that it doesn't have to be coerced again.

This line is different in 2.1 than in 2.0, but I think that it will have the same effect. I've been a bit behind on changes (and bad at looking at things when I said I would recently), so I could have missed something!

**Comment by chainsawriot** [comment]
TODOs

- [x] Fix this test case 

https://github.com/ropensci/readODS/blob/d9a2787679b353879b9f429d0bc68cdcabb62c90/tests/testthat/test_read_ods.R#L42C1-L43

- [x] Remove the data.frame call.

**Comment by chainsawriot** [comment]
@mafw Thank you for reporting this. And thank @pbrohan for chipping in.

It is now fixed. 


``` r
tempods <- tempfile(fileext = ".ods")
download.file("https://github.com/ropensci/readODS/raw/v2.1/tests/testdata/test_naming.ods", destfile = tempods)
readODS::read_ods(tempods, .name_repair = "minimal")
#> # A tibble: 5 × 3
#>       a a     ``    
#>   <dbl> <chr> <chr> 
#> 1     1 Val 1 Miss 1
#> 2     2 Val 2 Miss 2
#> 3     3 Val 3 Miss 3
#> 4     4 Val 4 Miss 4
#> 5     5 Val 5 Miss 5

readODS::read_ods(tempods) ## default unique
#> New names:
#> • `a` -> `a...1`
#> • `a` -> `a...2`
#> • `` -> `...3`
#> # A tibble: 5 × 3
#>   a...1 a...2 ...3  
#>   <dbl> <chr> <chr> 
#> 1     1 Val 1 Miss 1
#> 2     2 Val 2 Miss 2
#> 3     3 Val 3 Miss 3
#> 4     4 Val 4 Miss 4
#> 5     5 Val 5 Miss 5
```

<sup>Created on 2023-09-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


It is rather unfortunate that I uploaded a version on CRAN yesterday. I will need to wait a bit until a new version can be uploaded again.

At the mean time, please use the GitHub version.

```r
remotes::install_github("ropensci/readODS")
```

Sorry for inconvenience caused!
