### ISSUE TITLE
Argument `check.names`

### ISSUE THREAD

**Issue by grossbach** [ropensci/readODS#36]
Adding `check.names`, as in: `data.frame(..., check.names = TRUE`, as additional argument to `read_ODS` would be great, as it would give the user more freedom as to how column names would be created.

**Comment by ldanon** [comment]
Second this - it is difficult to deal with multiple columns with the same name currently.

**Comment by chainsawriot** [comment]
Fixed by 39f5bfaebbdcbc6483bc7ed68df17babc802ed6d
