### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by pufcan** [ropensci/readODS#37]
It is a great package and a big help, but with large files read_ods() is very slow, at least on my computer/usecase.

**Comment by chainsawriot** [comment]
Thank you! It is a known issue. I have a plan to rewrite the whole package from scratch using C++ later.

**Comment by Thomas-Hirsch** [comment]
I'm wondering, what's the status of the planned rewrite? The performance issue is a strong barrier to using this package. From experimentation, I've found that python's `ezodf` module works significantly faster, so I've been considering making an R wrapper using Reticulate. But obviously I'd prefer to have a properly-developed R solution than to try to make my own workaround
