### ISSUE TITLE
Speed of writing?

### ISSUE THREAD

**Issue by edent** [ropensci/readODS#49]
I have a dataframe `test` of ~80,000 obs of 9 variables. 

I tried to run `write_ods(test, "whatever.ods")` 

After 30 minutes the action still hadn't completed.

Smaller DF work. For example `write_ods(iris, "iris.ods")` completes nearly instantly.

Am I doing something wrong? Is there a filesize limitation?

**Comment by chainsawriot** [comment]
@edent I will say you should do nothing wrong. The `write_ods` is unoptimized. The writing of ods file is a double-loop process and have not been rewritten in C++ for example.

I did a simple benchmark of writing 1000 rows of a 9-column data frame and it took 22 seconds. 

If you need to write ods fast, a better approach is to first export your DF into csv using a heavily optimized solution such as `readr::write_csv`. And then use headless Libreoffice to convert the csv to ods.

`libreoffice --headless --convert-to ods test.csv`

On my machine, both operations (1. export to csv and 2. csv to ods) work almost instantly.

**Comment by chainsawriot** [comment]
@edent Sorry for the super late update.

Thanks to #88 , ODS writing is now 100x faster. As the following benchmark shows, writing 80000 rows, 9 columns can be finished in 13s (provided that `append` and `update` are FALSE).

If you want to try this, please install the latest Github version v1.8. It will be available on CRAN later.

I believe this still can be improved. But I hope it makes `write_ods` usable.

``` r
require(readODS)
#> Loading required package: readODS

set.seed(721831)
n <- 80000
df1 <- data.frame(a1 = sample(c(1:100), size = n, replace = TRUE),
                  b1 = sample(c(3.14, 3.1416, 12.345, 721.831), size = n, replace = TRUE),
                  c1 = sample(LETTERS, size = n, replace = TRUE),
                  d1 = sample(c(1L:100L), size = n, replace = TRUE),
                  a2 = sample(c(1:100), size = n, replace = TRUE),
                  b2 = sample(c(3.14, 3.1416, 12.345, 99.831), size = n, replace = TRUE),
                  c2 = sample(LETTERS, size = n, replace = TRUE),
                  d2 = sample(c(1L:100L), size = n, replace = TRUE),
                  a3 = sample(c(1L:100L), size = n, replace = TRUE))
system.time(write_ods(df1, path = tempfile(fileext = ".ods")))
#>    user  system elapsed 
#>  10.491   2.911  13.411

sessionInfo()
#> R version 4.2.2 Patched (2022-11-10 r83330)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.1 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] readODS_1.8.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.39        magrittr_2.0.3    R.cache_0.16.0    rlang_1.0.6      
#>  [5] fastmap_1.1.0     fansi_1.0.3       stringr_1.4.1     styler_1.7.0     
#>  [9] highr_0.9         tools_4.2.2       xfun_0.31         R.oo_1.25.0      
#> [13] utf8_1.2.2        cli_3.6.0         withr_2.5.0       htmltools_0.5.3  
#> [17] yaml_2.3.6        digest_0.6.30     tibble_3.1.8      lifecycle_1.0.3  
#> [21] purrr_1.0.1       vctrs_0.5.1       R.utils_2.12.0    fs_1.5.2         
#> [25] glue_1.6.2        evaluate_0.15     rmarkdown_2.14    reprex_2.0.1     
#> [29] stringi_1.7.12    compiler_4.2.2    pillar_1.8.1      R.methodsS3_1.8.2
#> [33] pkgconfig_2.0.3
```

<sup>Created on 2023-01-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
