### ISSUE TITLE
Issues from ropensci/software-review#386

### ISSUE THREAD

**Issue by chainsawriot** [ropensci/readODS#70]
ref ropensci/software-review#386

**Comment by chainsawriot** [comment]
Vig

- [ ] PlantGrowth
- [ ] write_ods

Doc

- [ ] pkg-doc
- [ ] examples
- [ ] emails
- [ ] write_ods unclear
- [ ] roxy cross-link
- [ ] deprecated
- [ ] TRUE / FALSE
- [ ] Title case

**Comment by mmahmoudian** [comment]
I also think the item "Title case" can be also marked as done which was supposed to be about the following reviewer's comment:

> Titles should be capitalised, "\title sections should be capitalized and not end in a period.", from https://developer.r-project.org/Rds.html.
