### ISSUE TITLE
Using `zip::zip`

### ISSUE THREAD

**Issue by MindcraftMax** [ropensci/readODS#99]
The read_ods function works fine, however the write_ods function does not work.
MWE:
```
setwd(correct_path)
# Test to see if read_ods finds the correct path and reads correctly:
read_ods("test_read.ods")  # does work
df <- data.frame(n = c(1,2,3), sqr = c(1,4,9))
write_ods(df, "test_write.ods")  # does run (no error) but no .ods file is created
```

I've looked at the R code for write_ods to see how it works, and indeed files have been created in the AppData Temp folder, with names: content.xml, meta.xml, mimetype, styles.xml, and a META-INF folder containing manifest.xml; but that's all, no .ods file is created at the working directory.
I have tested compressing manually the aforementioned files into a .zip and changing the extension from .zip to .ods, and it seems to work fine. So it must be a problem when zipping and/or creating the file in the directory.

**Comment by chainsawriot** [comment]
@MindcraftMax Thanks for the report. Do you have write permission to your "correct_path"?

It also reminds me that the current way of `write_ods` handling errors is not optimal.

**Comment by MindcraftMax** [comment]
Yes I have write permission, I tried to use saveRDS which works fine.

**Comment by chainsawriot** [comment]
@MindcraftMax  I can't reproduce this. My suspicion is the zip process isn't work in your OS (Could you post your `sessionInfo()`?). But anyway, I will remove the `tryCatch` block #100 .

https://github.com/ropensci/readODS/blob/9c725a192009996baa61750e68c3d8a14fc95967/R/writeODS.R#L186

``` r
require(readODS)
#> Loading required package: readODS
df <- data.frame(n = c(1,2,3), sqr = c(1,4,9))
write_ods(df, "test_write.ods")  # does run (no error) but no .ods file is created
file.exists("test_write.ods")
#> [1] TRUE
x <- read_ods("test_write.ods")
x
#>   n sqr
#> 1 1   1
#> 2 2   4
#> 3 3   9
sessionInfo()
#> R version 4.2.3 (2023-03-15)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.2 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] readODS_1.8.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.42        xml2_1.3.3        magrittr_2.0.3    hms_1.1.3        
#>  [5] R.cache_0.16.0    R6_2.5.1          rlang_1.1.0       fastmap_1.1.1    
#>  [9] fansi_1.0.4       styler_1.9.0      tools_4.2.3       xfun_0.37        
#> [13] R.oo_1.25.0       utf8_1.2.3        cli_3.6.1         withr_2.5.0      
#> [17] htmltools_0.5.4   yaml_2.3.7        digest_0.6.31     tibble_3.2.1     
#> [21] lifecycle_1.0.3   crayon_1.5.2      tzdb_0.3.0        purrr_1.0.1      
#> [25] readr_2.1.4       vctrs_0.6.1       R.utils_2.12.2    fs_1.6.1         
#> [29] glue_1.6.2        evaluate_0.20     rmarkdown_2.20    reprex_2.0.2     
#> [33] stringi_1.7.12    pillar_1.9.0      compiler_4.2.3    R.methodsS3_1.8.2
#> [37] pkgconfig_2.0.3
```

<sup>Created on 2023-04-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If you can, you can try this:

```r
debug(write_ods)
debug(readODS:::.zip_tmp_to_path)
df <- data.frame(n = c(1,2,3), sqr = c(1,4,9))
write_ods(df, "test_write.ods")
```

And tell me whether the above mentioned line gives you a sudden jump to the last.

**Comment by chainsawriot** [comment]
? https://stackoverflow.com/questions/29129681/create-zip-file-error-running-command-had-status-127

**Comment by MindcraftMax** [comment]
@chainsawriot
I've tested your debug code and haven't noticed any jump, but no zip file was created when utils::zip ran.
I tried to run utils::zip() in a standalone example and it did not return any error or status 127.
But I've looked at this thread which describes my problem: [R function zip(utils) doesn't work on my machine](https://stackoverflow.com/questions/12698583/r-function-ziputils-doesnt-work-on-my-machine), and [this one](https://stackoverflow.com/questions/66606230/zip-function-doesn%C2%B4t-work-in-r-studio-how-can-i-create-a-compressed-file-zip): **using zip() from the zip package** (instead of utils) fixes the problem and seems to be the only solution.
However, I don't know how to test it on write_ods.

Here is my session info:
```
> library(readODS)
> setwd("C:/Users/McM/Documents/Projet R")
> # Test to see if read_ods finds the correct path and reads correctly:
> read_ods("test_read.ods")  # does work
  x  fx
1 4  48
2 6 108
3 8 192
> df <- data.frame(n = c(1,2,3), sqr = c(1,4,9))
> write_ods(df, "test_write.ods")  # does run (no error) but no .ods file is created
> sessionInfo()
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621) 

Matrix products: default

locale:
[1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8    LC_MONETARY=French_France.utf8
[4] LC_NUMERIC=C                   LC_TIME=French_France.utf8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] readODS_1.8.0

loaded via a namespace (and not attached):
[1] fansi_1.0.4     crayon_1.5.2    tzdb_0.3.0      utf8_1.2.3      R6_2.5.1        lifecycle_1.0.3
[7] magrittr_2.0.3  pillar_1.9.0    stringi_1.7.12  rlang_1.1.0     cli_3.6.1       rstudioapi_0.14
[13] xml2_1.3.3      vctrs_0.6.1     tools_4.2.3     readr_2.1.4     glue_1.6.2      purrr_1.0.1
[19] hms_1.1.3       compiler_4.2.3  pkgconfig_2.0.3 tibble_3.2.1
```

**Comment by chainsawriot** [comment]
@MindcraftMax Could you please give this a try?

```r
remotes::install_github("ropensci/readODS", ref = "zip") ## You might restart your session if you want
require(readODS)
#> Loading required package: readODS
df <- data.frame(n = c(1,2,3), sqr = c(1,4,9))
write_ods(df, "test_write.ods")
file.exists("test_write.ods")
```

**Comment by MindcraftMax** [comment]
It works perfectly, It returns true and the .ods file is created fine.
